/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_MyLib */

#ifndef _Included_com_example_ndk_MyLib
#define _Included_com_example_ndk_MyLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_MyLib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndk_MyLib_add
  (JNIEnv *, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_com_example_ndk_MyLib_subtract
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
